### ISSUE TITLE
it seem code updated 3 week ago here, but pub.dev shows 8 month ago, so can't update from pub get

### ISSUE THREAD

**Issue by Ali-Fadaei** [bitsdojo/bitsdojo_window#219]

**Comment by edufolly** [comment]
You can use `dependency_overrides` to use the git repository.

```yaml
dependency_overrides:
  bitsdojo_window:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window

  bitsdojo_window_linux:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window_linux

  bitsdojo_window_macos:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window_macos

  bitsdojo_window_platform_interface:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window_platform_interface

  bitsdojo_window_windows:
    git:
      url: https://github.com/bitsdojo/bitsdojo_window.git
      path: bitsdojo_window_windows
```
