### ISSUE TITLE
No named parameter with the name 'nullOk'

### ISSUE THREAD

**Issue by lonadels** [bitsdojo/bitsdojo_window#26]
Hello. I can't build project with your library. I using flutter dev channel. How i can build on this version?

![cmd_sTb8I7cHv0](https://user-images.githubusercontent.com/15861168/106371792-ac6dc600-6379-11eb-9381-1c83146a01ff.png)

```
> flutter --version

Flutter 1.26.0-17.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision c40e5294dd (32 hours ago) • 2021-01-29 08:44:18 -0800
Engine • revision 5d3477eab4
Tools • Dart 2.12.0 (build 2.12.0-259.0.dev)
```

**Comment by escamoteur** [comment]
Hi, it's a problem of the transition period to null safety in flutter_svg

you can use my fork till this get settled:

```
  flutter_svg:  
    git:
      url: https://github.com/escamoteur/flutter_svg.git
      ref: maybe_of
```
